### ISSUE TITLE
example/data

### ISSUE THREAD

**Issue by 975z** [desmondlzy/embroidery-streamlines#1]
There is no feather.jpg, feather.json in the example/data , so run_multiple_patches.py cannot be run.

**Comment by MarkitoPlus** [comment]
I meet the same problem! Have you fixed it?

**Comment by desmondlzy** [comment]
@975z @MarkitoPlus I've just updated `run_multiple_patches.py` and also added `feather.jpg` and `feather.json` for your reference in commit bf738b4.  Pull from the repo again and you should be able to get it work.
