### ISSUE TITLE
Conda Packages on osx-arm64 cannot be found

### ISSUE THREAD

**Issue by dhr-nl** [desmondlzy/embroidery-streamlines#2]
Hi,

I was very interested in your project and the results that it would produce but I have issues getting the environment set up. I've already formatted my Mac. That would exclude any previous installations of some kind causing issues. 

When running conda create env as per instructions, the following error appears.

> 
>  Channels:
>  - conda-forge
>  - defaults
> Platform: osx-arm64
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - zstd==1.5.2=hbc0c0cd_6
>   - zlib-ng==2.0.7=hb7f2c08_0
>   - zlib==1.2.13=hfd90126_4
>   - zfp==1.0.0=ha894c9a_3
>   - zeromq==4.3.4=he49afe7_1
>   - yaml==0.2.5=h0d85af4_2
>   - xz==5.2.6=h775f41a_0
>   - xorg-libxdmcp==1.1.3=h35c211d_0
>   - xorg-libxau==1.0.9=h35c211d_0
>   - unicodedata2==15.0.0=py38hef030d1_0
>   - tornado==6.3=py38hef030d1_0
>   - tk==8.6.12=h5dbffcc_0
>   - sympy==1.11.1=py38h50d1736_2
>   - sqlite==3.40.0=h9ae0607_1
>   - snappy==1.1.10=h225ccf5_0
>   - sip==6.7.9=py38h940360d_0
>   - scipy==1.9.1=py38hb5a21b1_0
>   - scikit-learn==1.1.2=py38h27a3d75_0
>   - scikit-image==0.19.3=py38h1a4fe92_1
>   - reportlab==3.6.13=py38hd9f4822_0
>   - readline==8.2=h9e318b2_1
>   - qt-webengine==5.15.8=h84e7aee_0
>   - qt-main==5.15.8=h1d3b3f8_6
>   - qt==5.15.8=h93fa01e_0
>   - pyzmq==25.0.2=py38h0b711fd_0
>   - pyyaml==6.0=py38hef030d1_5
>   - pywavelets==1.4.1=py38hbd87e4b_0
>   - python==3.8.13=h66c20e1_0_cpython
>   - pyrsistent==0.19.3=py38hef030d1_0
>   - pyqt5-sip==12.11.0=py38haf9be31_3
>   - pyqt==5.15.7=py38h872f513_3
>   - pyobjc-framework-cocoa==9.1.1=py38h8f2a8f7_0
>   - pyobjc-core==9.1.1=py38h8f2a8f7_0
>   - pthread-stubs==0.4=hc929b4f_1001
>   - psutil==5.9.5=py38hef030d1_0
>   - pillow==9.4.0=py38hf04c7c8_1
>   - pcre2==10.40=h1c4e4bc_0
>   - pcre==8.45=he49afe7_0
>   - pandoc==2.19.2=h694c41f_2
>   - openssl==3.1.0=h8a1eda9_3
>   - openjpeg==2.5.0=h13ac156_2
>   - numpy==1.23.2=py38h84cd246_0
>   - numba==0.53.1=py38h5b9a75a_1
>   - nss==3.89=h78b00b3_0
>   - nspr==4.35=hea0b92c_0
>   - ncurses==6.3=h96cf925_1
>   - mysql-libs==8.0.32=haa61052_2
>   - mysql-common==8.0.32=hc6116ba_2
>   - mpfr==4.2.0=h4f9bd69_0
>   - mpc==1.3.1=h81bd1dd_0
>   - matplotlib-base==3.5.3=py38hae485fc_2
>   - matplotlib==3.5.3=py38h50d1736_2
>   - markupsafe==2.1.2=py38hef030d1_0
>   - lz4-c==1.9.4=hf0c8a7f_0
>   - lxml==4.9.2=py38h64add32_0
>   - llvmlite==0.36.0=py38h872f124_0
>   - llvm-openmp==16.0.3=hff08bdf_0
>   - libzopfli==1.0.3=h046ec9c_0
>   - libzlib==1.2.13=hfd90126_4
>   - libxslt==1.1.37=h5d22bc9_0
>   - libxml2==2.10.3=h201ad9d_4
>   - libxcb==1.13=h0d85af4_1004
>   - libwebp-base==1.2.4=h775f41a_0
>   - libwebp==1.2.4=h70a068d_1
>   - libvorbis==1.3.7=h046ec9c_0
>   - libtiff==4.5.0=hee9004a_2
>   - libssh2==1.10.0=h47af595_3
>   - libsqlite==3.40.0=ha978bb4_1
>   - libsodium==1.0.18=hbcb3906_1
>   - libpq==15.2=h3640bf0_0
>   - libpng==1.6.39=ha978bb4_0
>   - libopus==1.3.1=hc929b4f_1
>   - libopenblas==0.3.21=openmp_h429af6e_3
>   - libogg==1.3.4=h35c211d_1
>   - libnghttp2==1.52.0=he2ab024_0
>   - libllvm13==13.0.1=h64f94b2_2
>   - libllvm11==11.1.0=hd011deb_3
>   - libllvm10==10.0.1=h009f743_3
>   - liblapack==3.9.0=16_osx64_openblas
>   - libiconv==1.17=hac89ed1_0
>   - libglib==2.76.2=hc62aa5d_0
>   - libgfortran5==12.2.0=he409387_31
>   - libgfortran==5.0.0=11_3_0_h97931a8_31
>   - libffi==3.4.2=h0d85af4_5
>   - libev==4.33=haf1e3a3_1
>   - libedit==3.1.20191231=h0678c8f_2
>   - libdeflate==1.17=hac1461d_0
>   - libcxx==16.0.3=hd57cbcb_0
>   - libcurl==8.0.1=h1fead75_0
>   - libclang==13.0.1=default_h255f2f3_1
>   - libcblas==3.9.0=16_osx64_openblas
>   - libbrotlienc==1.0.9=hb7f2c08_8
>   - libbrotlidec==1.0.9=hb7f2c08_8
>   - libbrotlicommon==1.0.9=hb7f2c08_8
>   - libblas==3.9.0=16_osx64_openblas
>   - libavif==0.11.1=he9a59b1_0
>   - libaec==1.0.6=hf0c8a7f_1
>   - lerc==4.0.0=hb486fe8_0
>   - lcms2==2.15=h29502cd_0
>   - krb5==1.20.1=h049b76e_0
>   - kiwisolver==1.4.4=py38h98b9b1b_1
>   - jxrlib==1.1=h35c211d_2
>   - jupyter_core==5.3.0=py38h50d1736_0
>   - jupyter==1.0.0=py38h50d1736_7
>   - jpeg==9e=hb7f2c08_3
>   - imagecodecs==2023.1.23=py38h5408aff_0
>   - icu==70.1=h96cf925_0
>   - gstreamer==1.22.0=h1d18e73_2
>   - gst-plugins-base==1.22.0=h37e1711_2
>   - gmpy2==2.1.2=py38h919de47_1
>   - gmp==6.2.1=h2e338ed_0
>   - glib-tools==2.76.2=h7d26f99_0
>   - glib==2.76.2=h7d26f99_0
>   - giflib==5.2.1=hb7f2c08_3
>   - gettext==0.21.1=h8a4c099_0
>   - freetype==2.12.1=h3f81eb7_1
>   - fonttools==4.39.3=py38hef030d1_0
>   - expat==2.4.8=h96cf925_0
>   - debugpy==1.6.7=py38h4cd09af_0
>   - dbus==1.13.6=h811a1a6_3
>   - dav1d==1.0.0=hac89ed1_1
>   - cytoolz==0.12.0=py38hef030d1_1
>   - cryptography==40.0.2=py38h4257468_0
>   - charls==2.4.1=hf0c8a7f_0
>   - cfitsio==4.2.0=hd56cc12_0
>   - cffi==1.15.1=py38hb368cf1_3
>   - ca-certificates==2023.5.7=h8857fd0_0
>   - c-blosc2==2.8.0=had5f71b_1
>   - c-ares==1.18.1=h0d85af4_0
>   - bzip2==1.0.8=h0d85af4_4
>   - brunsli==0.1=h046ec9c_0
>   - brotlipy==0.7.0=py38hef030d1_1005
>   - brotli-bin==1.0.9=hb7f2c08_8
>   - brotli==1.0.9=hb7f2c08_8
>   - blosc==1.21.2=hebb52c4_0
>   - argon2-cffi-bindings==21.2.0=py38hef030d1_3
>   - aom==3.5.0=hf0c8a7f_0
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/osx-arm64
>   - https://repo.anaconda.com/pkgs/main/osx-arm64
>   - https://repo.anaconda.com/pkgs/r/osx-arm64
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

**Comment by desmondlzy** [comment]
@dhr-nl hi thanks for pointing this out! i've updated the dependency file. can you try creating the environment again with the latest version of this repo? on a mac, you might be needing to use `conda env create -f environment-arm64.yml`
